server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: fallback
            uri: http://localhost:8090
            predicates:
              - Path=/**
          - id: student-root
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/student, /api/v1/student/
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/student/**
          - id: schools
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/schools/**

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
logging:
  level:
    org.springframework.cloud.gateway: DEBUG